fix: the sum of probs passed to Categorical class is not 1
Traceback:
ValueError: Expected parameter probs (Tensor of shape (32, 1600)) of distribution Categorical(probs: torch.Size([32, 1600]))
to satisfy the constraint Simplex(), but found invalid values:
tensor([[9.8522e-06, 9.8522e-06, 9.8522e-06,  ..., 9.8522e-06, 9.8522e-06,
         9.8522e-06],
        [4.6062e-03, 9.8427e-06, 9.8427e-06,  ..., 9.8427e-06, 9.8427e-06,
         9.8427e-06],
        [1.3966e-03, 1.1960e-02, 6.7240e-04,  ..., 9.8427e-06, 9.8427e-06,
         9.8427e-06],
        ...,
        [9.8510e-06, 9.8510e-06, 9.8510e-06,  ..., 9.8510e-06, 9.8510e-06,
         9.8510e-06],
        [7.9161e-01, 9.8620e-06, 9.8620e-06,  ..., 9.8620e-06, 9.8620e-06,
         9.8620e-06],
        [6.2500e-04, 6.2500e-04, 6.2500e-04,  ..., 6.2500e-04, 6.2500e-04,
         6.2500e-04]], device='cuda:0', grad_fn=<DivBackward0>)

Fix approach:
`lx = lx + 1e-5` is the main cause to NaN, because this operation will make the sum of probs is not equal to 1, which is accepted by Categorical class.
Therefore, use `lx = th.clamp(lx, min=1e-10)` to avoid NaN and negative number.