fix: 1. support cuda 2. run out of memory by kfac optimizer. 3. torch._C._LinAlgError
Traceback:
Bug 1.
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params,
jobz, uplo, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(W), CUDA_R_32F,
reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost),
workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you
may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See
https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

Bug 3.
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnXsyevd( handle, params,
jobz, uplo, n, CUDA_R_32F, reinterpret_cast<void*>(A), lda, CUDA_R_32F, reinterpret_cast<void*>(W), CUDA_R_32F,
reinterpret_cast<void*>(bufferOnDevice), workspaceInBytesOnDevice, reinterpret_cast<void*>(bufferOnHost),
workspaceInBytesOnHost, info)`. This error may appear if the input matrix contains NaN. If you keep seeing this error, you
may use `torch.backends.cuda.preferred_linalg_library()` to try linear algebra operators with other supported backends. See
https://pytorch.org/docs/stable/backends.html#torch.backends.cuda.preferred_linalg_library

Fix approach:
1. change to another linalg library, add `th.backends.cuda.preferred_linalg_library("magma")` in acktr.py.
2. Split  `self.m_aa[m]`  and  `self.m_gg[m]` matrix into small block matrix, avoiding out of memory broblem when using `th.linalg.eigh`.
3. Doing regularization on the matrix  `self.m_aa[m]`  and  `self.m_gg[m]` passed to the `th.linalg.eigh` function by adding a small positive number to `self.m_aa[m]` and `self.m_gg[m]` during `optimizer.step()`.